# Cleaning the train_v2.csv and test_v2.csv datasets

**Objective:**

In this notebook we intend to clean the data by parsing it and removing unnecessary columns.

This will help us immensely by saving us some time.

We will save the cleaned data in two .csv files for future use.

**Data extraction**

In [2]:
library(plyr)
library(data.table)
library(tidyverse)
library(jsonlite)
library(magrittr)
library(caret)
library(lubridate)
library(dataPreparation)

Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Registered S3 method overwritten by 'rvest':
  method            from
  read_xml.response xml2
-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
v ggplot2 3.1.1       v purrr   0.3.2  
v tibble  2.1.1       v dplyr   0.8.0.1
v tidyr   0.8.3       v stringr 1.4.0  
v readr   1.3.1       v forcats 0.4.0  
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::arrange()   masks plyr::arrange()
x dplyr::between()   masks data.table::between()
x purrr::compact()   masks plyr::compact()
x dplyr::count()     masks plyr::count()
x dplyr::failwith()  masks plyr::failwith()
x dplyr::filter()    masks stats::filter()
x dplyr::first()     masks data.table::first()
x dplyr::id()        masks plyr::id()
x dplyr::lag()       masks stats::lag()
x dplyr::last()      masks data.table::last()
x dplyr::

In [3]:
ctypes <- cols(fullVisitorId = col_character(),
               channelGrouping = col_character(),
               date = col_datetime(),
               device = col_character(),
               geoNetwork = col_character(),
               socialEngagementType = col_skip(), 
               totals = col_character(),
               trafficSource = col_character(),
               visitId = col_integer(), 
               visitNumber = col_integer(),
               visitStartTime = col_integer(),
               hits = col_skip(),
               customDimensions = col_skip())

In [4]:
#WARNING!!!
#Dugo traje ucitavanje, you have been warned
###Data extraction without loading the socialEngagementType, hits and customDimensions columns
message("Data Extraction")
tr0 <- read_csv("C:/Users/Ivan/Desktop/Machine learning/Projekt/train_v2.csv", col_types = ctypes)
te0 <- read_csv("C:/Users/Ivan/Desktop/Machine learning/Projekt/test_v2.csv", col_types = ctypes)
print("Podaci uspjesno ucitani! :)")

Data Extraction


[1] "Podaci uspjesno ucitani! :)"


* loaded all columns except for socialEngagementType, hits and customDimensions
* socialEngagementType wasn't loaded because it is a constant column, which can immediately be seen at this link https://www.kaggle.com/c/ga-customer-revenue-prediction/data by clicking on the train_v2.csv under Data Sources and checking out the detailed view for that file. Its value is Not Socially Engaged for 100% of rows, which means that it is constant.
* customDimensions and hits weren't loaded mostly because of their unreadability. We suspect that those columns may be multiple level JSON columns, a problem for which we chose not to waste our time on.
* We suspect that the column hits also has somewhat of a shorter version in a subcolumn of JSON column totals (called hits also), so we feel that no relevant data has been lost with this exclusion.

**Dimensions**

In [6]:
#provjera ucitanih podataka
#vidi se da stupci device, geoNetwork, totals i trafficSource sadrzavaju hrpetinu podataka i necitljivi su u trenutnom obliku.
#ucitali smo samo 10 stupaca iz training i test seta, izostavili smo stupce socialEngagementType, hits i customDimensions.
dim(tr0)
dim(te0)
#training set ima 1708337 redaka i 10 stupaca
head(tr0,5)
#test set ima 401589 redaka i 10 stupaca
head(te0,5)
#training set je otprilike 4 puta veci od test seta

[1] 1708337      10

[1] 401589     10

channelGrouping date      
1 Organic Search  2017-10-16
2 Referral        2017-10-16
3 Direct          2017-10-16
4 Organic Search  2017-10-16
5 Organic Search  2017-10-16
  device                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
1 {"browser": "Firefox", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Windows", "operatingSystemVersion": "not available in demo dataset", "isMobile": false, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "desktop"} 
2 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Chrome OS", "operatingSystemVersion": "not available in demo dataset", "isMobile": false, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "desktop"}
3 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Android", "operatingSystemVersion": "not available in demo dataset", "isMobile": true, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "mobile"}    
4 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Windows", "operatingSystemVersion": "not available in demo dataset", "isMobile": false, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "desktop"}  
5 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "oper

channelGrouping date      
1 Organic Search  2018-05-11
2 Direct          2018-05-11
3 Organic Search  2018-05-11
4 Direct          2018-05-11
5 Organic Search  2018-05-11
  device                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
1 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Android", "operatingSystemVersion": "not available in demo dataset", "isMobile": true, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "mobile"}           
2 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Macintosh", "operatingSystemVersion": "not available in demo dataset", "isMobile": false, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "desktop"}       
3 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "Chrome OS", "operatingSystemVersion": "not available in demo dataset", "isMobile": false, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "desktop"}       
4 {"browser": "Chrome", "browserVersion": "not available in demo dataset", "browserSize": "not available in demo dataset", "operatingSystem": "iOS", "operatingSystemVersion": "not available in demo dataset", "isMobile": true, "mobileDeviceBranding": "not available in demo dataset", "mobileDeviceModel": "not available in demo dataset", "mobileInputSelector": "not available in demo dataset", "mobileDeviceInfo": "not available in demo dataset", "mobileDeviceMarketingName": "not available in demo dataset", "flashVersion": "not available in demo dataset", "language": "not available in demo dataset", "screenColors": "not available in demo dataset", "screenResolution": "not available in demo dataset", "deviceCategory": "mobile"}               
5 {"browser": "Internet Explorer", "browserVersion": "not available in demo dataset", "browse

* Train_v2.csv has 1708337 rows and 13 columns. We have successfully loaded 10 columns.
* Test_v2.csv has 401589 rows and 13 columns. We have successfully loaded 10 columns.
* Training dataset is roughly 4 times the size of the test dataset, which is a good trait.

**Parsing the JSON columns**

In [7]:
###Data parsing
#cinimo odredene stupce citljivijima i razdijeljujemo ih na puno vise stupaca

#definiramo fju flatten_json
flatten_json <- . %>% 
  str_c(., collapse = ",") %>% 
  str_c("[", ., "]") %>% 
  fromJSON(flatten = T)

#definiramo fju parse u kojoj koristimo flatten_json na problematicna 4 stupca
parse <- . %>% 
  bind_cols(flatten_json(.$device)) %>%
  bind_cols(flatten_json(.$geoNetwork)) %>% 
  bind_cols(flatten_json(.$trafficSource)) %>% 
  bind_cols(flatten_json(.$totals)) %>% 
  select(-device, -geoNetwork, -trafficSource, -totals)

In [67]:
message("Data Parsing")
tr <- parse(tr0)
te <- parse(te0)
print("Data parsed")

Data Parsing


[1] "Data parsed"


In [68]:
#pogledajmo sad što smo dobili
head(tr,5)
#imamo 57 stupaca u training setu (ovdje ne racunamo neucitana 3 stupca)
length(names(tr))
names(tr)

#imamo 56 stupaca u test setu, nedostaje stupac campaignCode
length(names(te))
names(te)

channelGrouping date       fullVisitorId       visitId    visitNumber
1 Organic Search  2017-10-16 3162355547410993243 1508198450 1          
2 Referral        2017-10-16 8934116514970143966 1508176307 6          
3 Direct          2017-10-16 7992466427990357681 1508201613 1          
4 Organic Search  2017-10-16 9075655783635761930 1508169851 1          
5 Organic Search  2017-10-16 6960673291025684308 1508190552 1          
  visitStartTime browser browserVersion               
1 1508198450     Firefox not available in demo dataset
2 1508176307     Chrome  not available in demo dataset
3 1508201613     Chrome  not available in demo dataset
4 1508169851     Chrome  not available in demo dataset
5 1508190552     Chrome  not available in demo dataset
  browserSize                   operatingSystem ... visits hits pageviews
1 not available in demo dataset Windows         ... 1      1    1        
2 not available in demo dataset Chrome OS       ... 1      2    2        
3 not available in demo dataset Android         ... 1      2    2        
4 not available in demo dataset Windows         ... 1      2    2        
5 not available in demo dataset Windows         ... 1      2    2        
  bounces newVisits sessionQualityDim timeOnSite transactions
1 1       1         1                 NA         NA          
2 NA      NA        2                 28         NA          
3 NA      1         1                 38         NA          
4 NA      1         1                 1          NA          
5 NA      1         1                 52         NA          
  transactionRevenue totalTransactionRevenue
1 NA                 NA                     
2 NA                 NA                     
3 NA                 NA                     
4 NA                 NA                     
5 NA                 NA

[1] 57

[1] "channelGrouping"                     "date"                               
 [3] "fullVisitorId"                       "visitId"                            
 [5] "visitNumber"                         "visitStartTime"                     
 [7] "browser"                             "browserVersion"                     
 [9] "browserSize"                         "operatingSystem"                    
[11] "operatingSystemVersion"              "isMobile"                           
[13] "mobileDeviceBranding"                "mobileDeviceModel"                  
[15] "mobileInputSelector"                 "mobileDeviceInfo"                   
[17] "mobileDeviceMarketingName"           "flashVersion"                       
[19] "language"                            "screenColors"                       
[21] "screenResolution"                    "deviceCategory"                     
[23] "continent"                           "subContinent"                       
[25] "country"                             "region"                             
[27] "metro"                               "city"                               
[29] "cityId"                              "networkDomain"                      
[31] "latitude"                            "longitude"                          
[33] "networkLocation"                     "campaign"                           
[35] "source"                              "medium"                             
[37] "keyword"                             "referralPath"                       
[39] "isTrueDirect"                        "adContent"                          
[41] "campaignCode"                        "adwordsClickInfo.criteriaParameters"
[43] "adwordsClickInfo.page"               "adwordsClickInfo.slot"              
[45] "adwordsClickInfo.gclId"              "adwordsClickInfo.adNetworkType"     
[47] "adwordsClickInfo.isVideoAd"          "visits"                             
[49] "hits"                                "pageviews"                          
[51] "bounces"                             "newVisits"                          
[53] "sessionQualityDim"                   "timeOnSite"                         
[55] "transactions"                        "transactionRevenue"                 
[57] "totalTransactionRevenue"

[1] 56

[1] "channelGrouping"                     "date"                               
 [3] "fullVisitorId"                       "visitId"                            
 [5] "visitNumber"                         "visitStartTime"                     
 [7] "browser"                             "browserVersion"                     
 [9] "browserSize"                         "operatingSystem"                    
[11] "operatingSystemVersion"              "isMobile"                           
[13] "mobileDeviceBranding"                "mobileDeviceModel"                  
[15] "mobileInputSelector"                 "mobileDeviceInfo"                   
[17] "mobileDeviceMarketingName"           "flashVersion"                       
[19] "language"                            "screenColors"                       
[21] "screenResolution"                    "deviceCategory"                     
[23] "continent"                           "subContinent"                       
[25] "country"                             "region"                             
[27] "metro"                               "city"                               
[29] "cityId"                              "networkDomain"                      
[31] "latitude"                            "longitude"                          
[33] "networkLocation"                     "referralPath"                       
[35] "campaign"                            "source"                             
[37] "medium"                              "keyword"                            
[39] "adContent"                           "isTrueDirect"                       
[41] "adwordsClickInfo.criteriaParameters" "adwordsClickInfo.page"              
[43] "adwordsClickInfo.slot"               "adwordsClickInfo.gclId"             
[45] "adwordsClickInfo.adNetworkType"      "adwordsClickInfo.isVideoAd"         
[47] "visits"                              "hits"                               
[49] "pageviews"                           "timeOnSite"                         
[51] "sessionQualityDim"                   "newVisits"                          
[53] "transactions"                        "transactionRevenue"                 
[55] "totalTransactionRevenue"             "bounces"

* After successful data parsing procedure, we now have 57 columns in the train set and 56 columns in the test set
* Since campaignCode appears only in the train set and not in the test set, we can remove it from further analysis

**Constant columns**

In [58]:
#trr<-tr
#c_cols<-whichAreConstant(trr)
#bug-ne pokretati

[1] "whichAreConstant: browserVersion is constant."
[1] "whichAreConstant: browserSize is constant."
[1] "whichAreConstant: operatingSystemVersion is constant."
[1] "whichAreConstant: mobileDeviceBranding is constant."
[1] "whichAreConstant: mobileDeviceModel is constant."
[1] "whichAreConstant: mobileInputSelector is constant."
[1] "whichAreConstant: mobileDeviceInfo is constant."
[1] "whichAreConstant: mobileDeviceMarketingName is constant."
[1] "whichAreConstant: flashVersion is constant."
[1] "whichAreConstant: language is constant."
[1] "whichAreConstant: screenColors is constant."
[1] "whichAreConstant: screenResolution is constant."
[1] "whichAreConstant: cityId is constant."
[1] "whichAreConstant: latitude is constant."
[1] "whichAreConstant: longitude is constant."
[1] "whichAreConstant: networkLocation is constant."
[1] "whichAreConstant: adwordsClickInfo.criteriaParameters is constant."
[1] "whichAreConstant: visits is constant."
[1] "whichAreConstant: it took me 6.95s to id

* We have identified a great deal of constant columns in our data using the whichAreConstant function.
* For some unknown reason, the usage of whichAreConstant function renders the "tr" dataframe useless, so we chose to handle the problem by simply defining the constant columns after reading them from the whichAreConstant function.
* It will prove wise to remove those constant columns from further analysis.

In [69]:
#Defining constant columns and removing them for speed and efficiency
const_cols_test = c('browserVersion',
 'browserSize',
 'operatingSystemVersion',
 'mobileDeviceBranding',
 'mobileDeviceModel',
 'mobileInputSelector',
 'mobileDeviceInfo',
 'mobileDeviceMarketingName',
 'flashVersion',
 'language',
 'screenColors',
 'screenResolution',
 'cityId',
 'latitude',
 'longitude',
 'networkLocation',
 'visits',
 'adwordsClickInfo.criteriaParameters')
const_cols_train = c(const_cols_test, 'campaignCode')

In [71]:
tr <- tr[, -which(names(tr) %in% c(const_cols_train))]

In [72]:
te<- te[ , -which(names(te) %in% c(const_cols_test))]

In [73]:
head(tr,5)
#tr
length(names(tr))
names(tr)
head(te,5)
length(names(te))
names(te)

channelGrouping date       fullVisitorId       visitId    visitNumber
1 Organic Search  2017-10-16 3162355547410993243 1508198450 1          
2 Referral        2017-10-16 8934116514970143966 1508176307 6          
3 Direct          2017-10-16 7992466427990357681 1508201613 1          
4 Organic Search  2017-10-16 9075655783635761930 1508169851 1          
5 Organic Search  2017-10-16 6960673291025684308 1508190552 1          
  visitStartTime browser operatingSystem isMobile deviceCategory ...
1 1508198450     Firefox Windows         FALSE    desktop        ...
2 1508176307     Chrome  Chrome OS       FALSE    desktop        ...
3 1508201613     Chrome  Android          TRUE    mobile         ...
4 1508169851     Chrome  Windows         FALSE    desktop        ...
5 1508190552     Chrome  Windows         FALSE    desktop        ...
  adwordsClickInfo.isVideoAd hits pageviews bounces newVisits sessionQualityDim
1 NA                         1    1         1       1         1                
2 NA                         2    2         NA      NA        2                
3 NA                         2    2         NA      1         1                
4 NA                         2    2         NA      1         1                
5 NA                         2    2         NA      1         1                
  timeOnSite transactions transactionRevenue totalTransactionRevenue
1 NA         NA           NA                 NA                     
2 28         NA           NA                 NA                     
3 38         NA           NA                 NA                     
4 1          NA           NA                 NA                     
5 52         NA           NA                 NA

[1] 38

[1] "channelGrouping"                "date"                          
 [3] "fullVisitorId"                  "visitId"                       
 [5] "visitNumber"                    "visitStartTime"                
 [7] "browser"                        "operatingSystem"               
 [9] "isMobile"                       "deviceCategory"                
[11] "continent"                      "subContinent"                  
[13] "country"                        "region"                        
[15] "metro"                          "city"                          
[17] "networkDomain"                  "campaign"                      
[19] "source"                         "medium"                        
[21] "keyword"                        "referralPath"                  
[23] "isTrueDirect"                   "adContent"                     
[25] "adwordsClickInfo.page"          "adwordsClickInfo.slot"         
[27] "adwordsClickInfo.gclId"         "adwordsClickInfo.adNetworkType"
[29] "adwordsClickInfo.isVideoAd"     "hits"                          
[31] "pageviews"                      "bounces"                       
[33] "newVisits"                      "sessionQualityDim"             
[35] "timeOnSite"                     "transactions"                  
[37] "transactionRevenue"             "totalTransactionRevenue"

channelGrouping date       fullVisitorId       visitId    visitNumber
1 Organic Search  2018-05-11 7460955084541987166 1526099341   2        
2 Direct          2018-05-11 460252456180441002  1526064483 166        
3 Organic Search  2018-05-11 3461808543879602873 1526067157   2        
4 Direct          2018-05-11 975129477712150630  1526107551   4        
5 Organic Search  2018-05-11 8381672768065729990 1526060254   1        
  visitStartTime browser           operatingSystem isMobile deviceCategory ...
1 1526099341     Chrome            Android          TRUE    mobile         ...
2 1526064483     Chrome            Macintosh       FALSE    desktop        ...
3 1526067157     Chrome            Chrome OS       FALSE    desktop        ...
4 1526107551     Chrome            iOS              TRUE    mobile         ...
5 1526060254     Internet Explorer Windows          TRUE    tablet         ...
  adwordsClickInfo.isVideoAd hits pageviews timeOnSite sessionQualityDim
1 NA                         4    3         973        1                
2 NA                         4    3         49         1                
3 NA                         4    3         24         1                
4 NA                         5    4         25         1                
5 NA                         5    4         49         1                
  newVisits transactions transactionRevenue totalTransactionRevenue bounces
1 NA        NA           NA                 NA                      NA     
2 NA        NA           NA                 NA                      NA     
3 NA        NA           NA                 NA                      NA     
4 NA        NA           NA                 NA                      NA     
5 1         NA           NA                 NA                      NA

[1] 38

[1] "channelGrouping"                "date"                          
 [3] "fullVisitorId"                  "visitId"                       
 [5] "visitNumber"                    "visitStartTime"                
 [7] "browser"                        "operatingSystem"               
 [9] "isMobile"                       "deviceCategory"                
[11] "continent"                      "subContinent"                  
[13] "country"                        "region"                        
[15] "metro"                          "city"                          
[17] "networkDomain"                  "referralPath"                  
[19] "campaign"                       "source"                        
[21] "medium"                         "keyword"                       
[23] "adContent"                      "isTrueDirect"                  
[25] "adwordsClickInfo.page"          "adwordsClickInfo.slot"         
[27] "adwordsClickInfo.gclId"         "adwordsClickInfo.adNetworkType"
[29] "adwordsClickInfo.isVideoAd"     "hits"                          
[31] "pageviews"                      "timeOnSite"                    
[33] "sessionQualityDim"              "newVisits"                     
[35] "transactions"                   "transactionRevenue"            
[37] "totalTransactionRevenue"        "bounces"

**Finishing remarks**

* As we can see, after starting from a parsed total of 60 columns we went through the process of data engineering and have ended up with only 38 columns.
* This will significantly improve speed and efficiency in our code.
* We will save the cleaned data to train_v2_cleaned.csv and test_v2_cleaned.csv for future use.

In [74]:
#saving the parsed and cleaned data to .csv
#write.csv(tr,"C:\\Users\\Ivan\\Desktop\\train_v2_cleaned.csv", row.names = FALSE)

In [75]:
#write.csv(te,"C:\\Users\\Ivan\\Desktop\\test_v2_cleaned.csv", row.names = FALSE)